networks:
  default: ~
volumes:
  mysql-db:

services:
  nginx:
    build:
      context: ./tasks/docker
      dockerfile: nginx.dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www/html

    depends_on:
      - app
    networks:
      - default
  app:
    build:
      context: ./tasks/docker
      dockerfile: php.dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    ports:
      - "9000:9000"
    volumes:
      - ./src:/var/www/html
    networks:
      - default

  db:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: schulinck
      MYSQL_USER: schulinck
      MYSQL_PASSWORD: test123
      MYSQL_ROOT_PASSWORD: root123
    ports:
      - '3306:3306'
    expose:
      - '3306:3306'
    volumes:
      - mysql-db:/var/lib/mysql

  composer:
    build:
      context: ./tasks/docker
      dockerfile: php.dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    volumes:
      - ./src:/var/www/html
    depends_on:
      - app
    entrypoint: [ 'composer' ]
    networks:
      - default


  npm:
    image: node:current-alpine
    volumes:
      - ./src:/var/www/html
    ports:
      - "3000:3000"
      - "3001:3001"
      - "5173:5173"
    working_dir: /var/www/html
    entrypoint: [ 'npm', 'run', 'watch' ]
    networks:
      - default
